# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_timetracker_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetracker',
            name='date',
        ),
        migrations.RemoveField(
            model_name='timetracker',
            name='time',
        ),
    ]
